// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mytvlistapi.Models;

namespace mytvlistapi.Migrations
{
    [DbContext(typeof(mytvlistapiContext))]
    [Migration("20181122091320_newCreate1")]
    partial class newCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("mytvlistapi.Models.TvItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authentication");

                    b.Property<string>("Author");

                    b.Property<string>("Comments");

                    b.Property<string>("EndDate");

                    b.Property<string>("Height");

                    b.Property<string>("Priority");

                    b.Property<string>("Progress");

                    b.Property<string>("Score");

                    b.Property<string>("StartDate");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("TvItem");
                });
#pragma warning restore 612, 618
        }
    }
}
